### ISSUE TITLE
Replace SLF4J with Log4J 2

### ISSUE THREAD

**Issue by MariusVolkhart** [MariusVolkhart/syncthing-lite#2]
Log4J 2 has made many improvements in terms of performance. The API they expose is different than SLF4J, and is necessary to take advantage of some of those improvements. Furthermore, we have more experience in configuring Log4J.

## Implementation
- Make use of the `LogBuilder` interface in the latest version of Log4J. Don't use the common `Logger.warn()`, Logger.debug()`, etc. functions.
- Make use of the `Unbox` class and the factory functions it provides

**Comment by MatthewFoster624** [comment]
Took a first pass at this, also adding any clarifications to the messaging where easily added.
One question I have is anywhere I entered `private val LOGGER = LogManager.getLogger(javaClass)`, it underlines `LOGGER` and gives me a warning that it doesn't match the key `{#a-z}` etc. I haven't found any issues, or any notes online about it yet.

**Comment by MariusVolkhart** [comment]
i wouldn't worry about it too much right now. probably some style enforcer that needs to be configured. make a PR when you want me to review the code
