### ISSUE TITLE
Remove Apache Commons Lang3

### ISSUE THREAD

**Issue by MariusVolkhart** [MariusVolkhart/syncthing-lite#3]
The `syncthing-core` module relies on Apache Commons Lang3. The only this being used from it is `Pair`, and only in internal APIs. We should use Kotlin's `Pair` instead, and avoid the dependency on Commons Lang3.

**Comment by mscibilia** [comment]
PR opened

**Comment by MariusVolkhart** [comment]
Closed by #6
